//
//  JZBPredefinedNotification.h
//  JZB
//
//  Created by Jin Jin on 11-4-7.
//  Copyright 2011年 __MyCompanyName__. All rights reserved.
//


#define NOTIFICATION_SYNC_START @"NOTIFICATION_SYNC_START"
#define NOTIFICATION_SYNC_END   @"NOTIFICATION_SYNC_END"
#define NOTIFICATION_SYNC_ERROR @"NOTIFICATION_SYNC_ERROR"
#define NOTIFICATION_SYNC_ERROR_NETWORK @"NOTIFICATION_SYNC_ERROR_NETWORK"
#define NOTIFICATION_SYNC_ERROR_USERNAME @"NOTIFICATION_SYNC_ERROR_USERNAME" 
#define NOTIFICATION_SYNC_ERROR_UNKNOWN @"NOTIFICATION_SYNC_ERROR_UNKNOWN"
#define NOTIFICATION_EDIT_ITEM_CLICKED  @"NOTIFICATION_EDIT_ITEM_CLICKED"
#define NOTIFICATION_ADD_ITEM_CLICKED   @"NOTIFICATION_ADD_ITEM_CLICKED"
#define NOTIFICATOIN_NEW_ACCOUNT_CREATED @"NOTIFICATOIN_NEW_ACCOUNT_CREATED"
#define NOTIFICATION_NEW_CATALOG_CREATED @"NOTIFICATION_NEW_CATALOG_CREATED"
#define NOTIFICATION_NEW_BILL_CREATED    @"NOTIFICATION_NEW_BILL_CREATED"




